import { Metadata } from "next";
import "../../global.css"
export const metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial",
    template: "%s | CodeEvolution" 
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-300 p-10">
          Header
        </header>
        {children}
        <p className="bg-blue-300 p-10">Footer</p>
      </body>
    </html>
  );
}
